# Site settings
# -------------
baseurl     : "" # the subpath of your site, e.g. /blog/
colour      : primary
language    : nl
host        : 127.0.0.1
port        : 4000

# SEO
# ---
title      : &title TROTS
description: "This is an assignment for Artevelde University College Ghent."
author     : Arteveldehogeschool Gent
tracking_id: ""
# url        :
# image      :
# Build settings
# --------------
# --------------
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
permalink: pretty
collections:
  projects:
    output: true
    permalink: /project/:slug
  stories:
    output: false
  news:
    output: true
    permalink: /news/:title/
defaults:
    - scope:
        path: ""
        type: projects
      values:
        layout: "detail"
        thumbnail:
            height: 1
            width: 1
            color: 1
exclude:
  - Gemfile
  - LICENSE
  - README.md