# Site settings
# -------------
baseurl     : "" # the subpath of your site, e.g. /blog/
colour      : primary
language    : nl
host        : 127.0.0.1
port        : 4000

# SEO
# ---
title      : &title TROTS
description: "This is an assignment for Artevelde University College Ghent."
author     : Jens De Wulf & Lotte Verwerft
tracking_id: ""
# url        :
# image      :
# Build settings
# --------------
# --------------
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
collections:
  projects:
    output: true
    permalink: /project/:title/
    defaults:
      values:
        layout: detail
exclude:
  - Gemfile
  - LICENSE
  - README.md